app.backup.path=./backups/
app.logs.path=./logs/

db.url=jdbc:mysql://localhost:3306/employee_management
db.username=YOUR_DB_USERNAME
db.password=YOUR_DB_PASSWORD

email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.username=YOUR_EMAIL
email.password=YOUR_EMAIL_PASSWORD
