#Application Configuration
#Fri Nov 07 20:55:48 IST 2025
app.backup.path=./backups/
app.logs.path=./logs/
app.theme=light
db.password=3008
db.url=jdbc\:mysql\://localhost\:3306/employee_management
db.username=root
email.password=Manoj@123
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.username=manojcs6317@gmail.com
